CREATE DATABASE IF NOT EXISTS ASSISTENCIA_TECNICA;

CREATE TABLE IF NOT EXISTS ASSISTENCIA_TECNICA.CLIENTES(
	ID INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    CPF VARCHAR(11) NOT NULL UNIQUE KEY,
    NOME VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS ASSISTENCIA_TECNICA.ASSISTENCIAS(
	ID INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    ENDERECO VARCHAR(255) NOT NULL,
    NOME VARCHAR (30) NOT NULL
);

CREATE TABLE IF NOT EXISTS ASSISTENCIA_TECNICA.PRODUTOS(
	ID INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    DESCRICAO_PRODUTO VARCHAR(30)
);

CREATE TABLE IF NOT EXISTS ASSISTENCIA_TECNICA.AGENDAMENTOS(
	ID INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    ID_CLIENTE INT UNSIGNED NOT NULL,
    ID_ASSISTENCIA INT UNSIGNED NOT NULL,
    ID_PRODUTO INT UNSIGNED NOT NULL,
    DATAS DATE NOT NULL,
    HORARIO TIME NOT NULL,
    CONSTRAINT FK_CLIENTE FOREIGN KEY(ID_CLIENTE) REFERENCES ASSISTENCIA_TECNICA.CLIENTES(ID),
    CONSTRAINT FK_ASSISTENCIA FOREIGN KEY(ID_ASSISTENCIA) REFERENCES ASSISTENCIA_TECNICA.ASSISTENCIAS(ID),
    CONSTRAINT FK_PRODUTO FOREIGN KEY(ID_PRODUTO) REFERENCES ASSISTENCIA_TECNICA.PRODUTOS(ID)
);
