CREATE DATABASE IF NOT EXISTS ASSISTENCIA_TECNICA;

CREATE TABLE IF NOT EXISTS ASSISTENCIA_TECNICA.CLIENTE(
	ID INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    CPF VARCHAR(11) NOT NULL UNIQUE KEY,
    NOME VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS ASSISTENCIA_TECNICA.ASSISTENCIAS(
	ID INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    ENDERECO VARCHAR(100) NOT NULL,
    NOME VARCHAR (30)
);

CREATE TABLE IF NOT EXISTS ASSISTENCIA_TECNICA.PRODUTOS(
	ID INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    DESCRICAO_PRODUTO VARCHAR(30)
);

CREATE TABLE IF NOT EXISTS ASSISTENCIA_TECNICA.DATAS(
	ID INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    DESCRICAO_DATA DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS ASSISTENCIA_TECNICA.HORARIOS(
	ID INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    DESCRICAO_HORARIO TIME NOT NULL
);

CREATE TABLE IF NOT EXISTS ASSISTENCIA_TECNICA.DATAS_HORARIOS(
	ID_DATA INT UNSIGNED NOT NULL,
    ID_HORARIO INT UNSIGNED NOT NULL,
    PREENCHIDO BOOLEAN NOT NULL,
    CONSTRAINT FK_DATA FOREIGN KEY(ID_DATA) REFERENCES ASSISTENCIA_TECNICA.DATAS(ID),
    CONSTRAINT FK_HORARIO FOREIGN KEY(ID_HORARIO) REFERENCES ASSISTENCIA_TECNICA.HORARIOS(ID)
);

CREATE TABLE IF NOT EXISTS ASSISTENCIA_TECNICA.ASSISTENCIA_DATAS_HORARIOS(
	ID_ASSISTENCIA INT UNSIGNED NOT NULL,
    ID_DATA INT UNSIGNED NOT NULL,
    ID_HORARIO INT UNSIGNED NOT NULL,
    PREENCHIDO BOOLEAN NOT NULL,
    CONSTRAINT FK_ASSISTENCIA FOREIGN KEY(ID_ASSISTENCIA) REFERENCES ASSISTENCIA_TECNICA.ASSISTENCIAS(ID),
    CONSTRAINT FK_DATA_DATAHORA FOREIGN KEY(ID_DATA) REFERENCES ASSISTENCIA_TECNICA.DATAS_HORARIOS(ID_DATA),
    CONSTRAINT FK_HORARIO_DATAHORA FOREIGN KEY(ID_HORARIO) REFERENCES ASSISTENCIA_TECNICA.DATAS_HORARIOS(ID_HORARIO)
);

CREATE TABLE IF NOT EXISTS ASSISTENCIA_TECNICA.AGENDAMENTO(
	ID INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    ID_CLIENTE INT UNSIGNED NOT NULL,
    ID_ASSISTENCIA INT UNSIGNED NOT NULL,
    ID_DATA INT UNSIGNED NOT NULL,
    ID_HORARIO INT UNSIGNED NOT NULL,
    CONSTRAINT FK_CLIENTE FOREIGN KEY(ID_CLIENTE) REFERENCES ASSISTENCIA_TECNICA.CLIENTE(ID),
    CONSTRAINT FK_ASSISTENCIA_ASSISTENCIADATAHORA FOREIGN KEY(ID_ASSISTENCIA) REFERENCES ASSISTENCIA_TECNICA.ASSISTENCIA_DATAS_HORARIOS(ID_ASSISTENCIA),
    CONSTRAINT FK_DATA_ASSISTENCIADATAHORA FOREIGN KEY(ID_DATA) REFERENCES ASSISTENCIA_TECNICA.ASSISTENCIA_DATAS_HORARIOS(ID_DATA),
    CONSTRAINT FK_HORARIO_ASSISTENCIADATAHORA FOREIGN KEY(ID_HORARIO) REFERENCES ASSISTENCIA_TECNICA.ASSISTENCIA_DATAS_HORARIOS(ID_HORARIO)
);
