CREATE DATABASE IF NOT EXISTS TECHNICAL_ASSISTANCE;

CREATE TABLE IF NOT EXISTS TECHNICAL_ASSISTANCE.CUSTOMERS(
	ID INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    CPF VARCHAR(11) NOT NULL UNIQUE KEY,
    NAME VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS TECHNICAL_ASSISTANCE.ASSISTANCES(
	ID INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    ADDRESS VARCHAR(255) NOT NULL,
    NAME VARCHAR (30) NOT NULL
);

CREATE TABLE IF NOT EXISTS TECHNICAL_ASSISTANCE.PRODUCTS(
	ID INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    PRODUCT_DESCRIPTION VARCHAR(30)
);

CREATE TABLE IF NOT EXISTS TECHNICAL_ASSISTANCE.APPOINTMENTS(
	ID INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    ID_CUSTOMER INT UNSIGNED NOT NULL,
    ID_ASSISTANCE INT UNSIGNED NOT NULL,
    ID_PRODUCT INT UNSIGNED NOT NULL,
    DATES DATE NOT NULL,
    HOURS TIME NOT NULL,
    CONSTRAINT FK_CUSTOMER FOREIGN KEY(ID_CUSTOMER) REFERENCES TECHNICAL_ASSISTANCE.CUSTOMERS(ID),
    CONSTRAINT FK_ASSISTANCE FOREIGN KEY(ID_ASSISTANCE) REFERENCES TECHNICAL_ASSISTANCE.ASSISTANCES(ID),
    CONSTRAINT FK_PRODUCT FOREIGN KEY(ID_PRODUCT) REFERENCES TECHNICAL_ASSISTANCE.PRODUCTS(ID),
    CONSTRAINT UN_APPOINTMENT UNIQUE(ID_ASSISTANCE, DATES, HOURS)
);
